# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-07-01 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=10, verbose_name='客户端')),
                ('score', models.IntegerField(verbose_name='分数')),
            ],
        ),
    ]
