# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-07-01 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Score',
            new_name='Client',
        ),
    ]
