# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-07-01 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0002_auto_20200701_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.AlterField(
            model_name='client',
            name='client',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='客户端'),
        ),
    ]
